services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshop_1
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data
    restart: unless-stopped
